# Generated by Django 4.2.14 on 2024-07-31 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('equipment_name', models.CharField(max_length=255)),
                ('checked_in', models.BooleanField(default=True)),
                ('checked_out_date', models.DateField(blank=True, null=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.technician')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='users.userprofile')),
            ],
            options={
                'unique_together': {('barcode', 'user_profile')},
            },
        ),
    ]
